// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function getValidSupabaseUrl(rawUrl?: string): string | null {
  if (!rawUrl || typeof rawUrl !== "string") return null;
  const trimmed = rawUrl.trim();
  if (
    !trimmed ||
    trimmed === "undefined" ||
    trimmed === "null" ||
    trimmed.includes("placeholder")
  ) {
    return null;
  }
  if (trimmed.startsWith("http://") || trimmed.startsWith("https://")) return trimmed;
  if (trimmed.includes(".") || trimmed.includes("localhost")) return `https://${trimmed}`;
  return null;
}

function getValidSupabaseKey(rawKey?: string): string | null {
  if (!rawKey || typeof rawKey !== "string") {
    return null;
  }
  const trimmed = rawKey.trim();
  if (
    !trimmed ||
    trimmed === "undefined" ||
    trimmed === "null" ||
    trimmed.includes("placeholder") ||
    trimmed.length < 20
  ) {
    return null;
  }
  return trimmed;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    (typeof process !== "undefined" ? process.env?.SUPABASE_URL : undefined);
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    (typeof process !== "undefined" ? process.env?.SUPABASE_PUBLISHABLE_KEY : undefined);

  const validUrl = getValidSupabaseUrl(SUPABASE_URL);
  const validKey = getValidSupabaseKey(SUPABASE_PUBLISHABLE_KEY);

  if (!validUrl || !validKey) {
    console.error(
      "[Supabase] Missing or invalid VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY",
    );
    throw new Error(
      "Supabase environment variables are not configured. Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.",
    );
  }

  return createClient<Database>(validUrl, validKey, {
    global: {
      fetch: createSupabaseFetch(validKey),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export function isSupabaseConfigured(): boolean {
  const url =
    import.meta.env.VITE_SUPABASE_URL ||
    (typeof process !== "undefined" ? process.env?.SUPABASE_URL : undefined);
  const key =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    (typeof process !== "undefined" ? process.env?.SUPABASE_PUBLISHABLE_KEY : undefined);
  if (!url || !key) return false;
  const trimmedUrl = String(url).trim();
  const trimmedKey = String(key).trim();
  return (
    trimmedUrl.startsWith("http") &&
    trimmedUrl.length > 10 &&
    !trimmedUrl.includes("placeholder") &&
    trimmedKey.length >= 20 &&
    trimmedKey !== "farooq"
  );
}

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) {
      try {
        _supabase = createSupabaseClient();
      } catch (err) {
        console.error("[Supabase] Failed to initialize client:", err);
        throw err;
      }
    }
    return Reflect.get(_supabase, prop, receiver);
  },
});
